# Telco Customer Churn: Pandas & NumPy Business Analysis

## Scenario
You are a junior data analyst working for a telecommunications company. Management is concerned about customer churn and wants to understand **who is leaving, which customer groups are most at risk, and where the business should focus retention efforts**.

In this activity, you will use the Pandas and NumPy techniques covered in class to turn the customer-level data into simple business insights.

### Learning goals
By the end of the activity, you should be able to:
- inspect a real-world dataset using Pandas
- select rows and columns
- filter data using multiple conditions
- use Series and NumPy statistics
- create simple derived calculations
- use `groupby()` to compare customer segments
- use pivot tables to summarize business metrics
- use NumPy arrays for numerical analysis

### Dataset
The file `Telco-Customer-Churn.csv` contains customer information such as contract type, tenure, monthly charges, services, and churn status.

**Important:** Do not change the original `data` DataFrame unless an exercise explicitly asks you to. Use `.copy()` when you need a working copy.

## 0. Load the data

Run the cell below to import the libraries and load the dataset.

In [169]:
import numpy as np
import pandas as pd

data = pd.read_csv('Telco-Customer-Churn.csv')
data_copy = data.copy()

data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

---
# Part 1 — Get to Know the Customer Base

## Exercise 1: Check the data before making business decisions

Before analyzing churn, an analyst should understand the size and structure of the customer base.

1. Display the first 5 rows.
2. Display the last 5 rows.
3. Check the number of rows and columns.
4. Use `info()` to inspect the columns and data types.
5. Use `describe()` to summarize the numerical columns.

**Business question:** How large is the customer base, and which numerical variables could be useful for understanding customer behavior?

In [170]:
# Your work here
#1. Display the first 5 rows.
data.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [171]:
# 2. Display the last 5 rows.
data.tail(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7004,6075-SLNIL,Male,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Credit card (automatic),95.10,3691.2,No
7005,9347-AERRL,Male,0,Yes,No,23,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),19.30,486.2,No
7006,0093-XWZFY,Male,0,No,No,40,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Credit card (automatic),104.50,4036.85,Yes
7007,2274-XUATA,Male,1,Yes,No,72,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),63.10,4685.55,No
7008,1980-KXVPM,Female,1,No,No,3,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Credit card (automatic),75.05,256.25,Yes

In [172]:
# 3. Check the number of rows and columns.
rows, cols = data.shape
print("Rows: ", rows)
print("Columns: ", cols)

Rows:  7009
Columns:  21

In [173]:
# 4. Use `info()` to inspect the columns and data types.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7009 entries, 0 to 7008
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7009 non-null   object
 1   gender            7009 non-null   object
 2   SeniorCitizen     7009 non-null   int64
 3   Partner           7009 non-null   object
 4   Dependents        7009 non-null   object
 5   tenure            7009 non-null   int64
 6   PhoneService      7009 non-null   object
 7   MultipleLines     7009 non-null   object
 8   InternetService   7009 non-null   object
 9   OnlineSecurity    7009 non-null   object
 10  OnlineBackup      7009 non-null   object
 11  DeviceProtection  7009 non-null   object
 12  TechSupport       7009 non-null   object
 13  StreamingTV       7009 non-null   object
 14  StreamingMovies   7009 non-null   object
 15  Contract          7009 non-null   object
 16  PaperlessBilling  7009 non-null   object
 17  PaymentMethod     7009 non-null   object
 18  MonthlyCharges    7009 non-null   float64
 19  TotalCharges      7009 non-null   object
 20  Churn             7009 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [174]:
# 5. Use `describe()` to summarize the numerical columns.
data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7009.000000  7009.000000     7009.000000
mean        0.161935    32.377372       64.746305
std         0.368417    24.556125       30.104056
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.450000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

## Exercise 2: Explore key customer characteristics

Management wants a quick overview of the customer base.

1. Find the unique values in `Contract`.
2. Find the unique values in `InternetService`.
3. Find the unique values in `PaymentMethod`.
4. Find the minimum, maximum, and average `MonthlyCharges`.
5. Find the minimum and maximum `tenure`.

**Business question:** What types of products and contracts are represented in the customer base, and what does a typical monthly charge look like?

In [175]:
# Your work here
# 1. Find the unique values in `Contract`.
data["Contract"].unique().tolist()

['Month-to-month', 'One year', 'Two year']

In [176]:
# 2. Find the unique values in `InternetService`.
data["InternetService"].unique().tolist()

['DSL', 'Fiber optic', 'No']

In [177]:
# 3. Find the unique values in `PaymentMethod`.
data["PaymentMethod"].unique().tolist()

['Electronic check',
 'Mailed check',
 'Bank transfer (automatic)',
 'Credit card (automatic)']

In [178]:
# 4. Find the minimum, maximum, and average `MonthlyCharges`.
min_MonthlyCharges = data["MonthlyCharges"].min()
max_MonthlyCharges = data["MonthlyCharges"].max()
ave_MonthlyCharges = data["MonthlyCharges"].mean()

print("Monthly Charges ")
print("minimum: ", min_MonthlyCharges)
print("maximum: ", max_MonthlyCharges)
print("average: ", ave_MonthlyCharges)

Monthly Charges
minimum:  18.25
maximum:  118.75
average:  64.74630475103439

In [179]:
# 5. Find the minimum and maximum `tenure`.
min_MonthlyCharges = data["tenure"].min()
max_MonthlyCharges = data["tenure"].max()
print("Tenure")
print("minimum: ", min_MonthlyCharges)
print("maximum: ", max_MonthlyCharges)

Tenure
minimum:  0
maximum:  72

---
# Part 2 — Churn Customers

## Exercise 3: Build a churn-focused customer view

The retention team wants to study customers who have already left.

1. Create a DataFrame called `churned` containing only customers where `Churn == 'Yes'`.
2. From `churned`, display only these columns:
   - `customerID`
   - `Contract`
   - `tenure`
   - `MonthlyCharges`
   - `InternetService`
   - `PaymentMethod`
   - `Churn`

**Business question:** What does the customer-level data for churned customers look like?

In [180]:
# Your work here
churned = data[(data['Churn'] == 'Yes')]
churned[['customerID','Contract', 'tenure','MonthlyCharges','InternetService','PaymentMethod','Churn']]

,customerID,Contract,tenure,MonthlyCharges,InternetService,PaymentMethod,Churn
2,3668-QPYBK,Month-to-month,2,53.85,DSL,Mailed check,Yes
4,9237-HQITU,Month-to-month,2,70.70,Fiber optic,Electronic check,Yes
5,9305-CDSKC,Month-to-month,8,99.65,Fiber optic,Electronic check,Yes
8,7892-POOKP,Month-to-month,28,104.80,Fiber optic,Electronic check,Yes
13,0280-XJGEX,Month-to-month,49,103.70,Fiber optic,Bank transfer (automatic),Yes
...,...,...,...,...,...,...,...
6996,4174-LPGTI,One year,41,66.50,DSL,Bank transfer (automatic),Yes
6999,2108-XWMPY,Month-to-month,3,35.45,DSL,Mailed check,Yes
7001,6304-IJFSQ,Month-to-month,3,49.90,DSL,Mailed check,Yes
7006,0093-XWZFY,Month-to-month,40,104.50,Fiber optic,Credit card (automatic),Yes
7008,1980-KXVPM,Month-to-month,3,75.05,Fiber optic,Credit card (automatic),Yes

## Exercise 4: Find high-value churned customers

Suppose the retention team wants to prioritize customers who have **already churned and were paying more than $80 per month**.

1. Filter the original dataset to customers satisfying both conditions.
2. Display `customerID`, `Contract`, `tenure`, and `MonthlyCharges`.
3. How many customers meet these conditions?

**Business question:** How many higher-paying customers have been lost and may deserve special attention in a retention review?

In [181]:
# Your work here
churned_high_paying = data[
    (data['Churn'] == 'Yes') &
    (data['MonthlyCharges'] > 80)
]

churned_high_paying[['customerID', 'Contract', 'tenure', 'MonthlyCharges']]

      customerID        Contract  tenure  MonthlyCharges
5     9305-CDSKC  Month-to-month       8           99.65
8     7892-POOKP  Month-to-month      28          104.80
13    0280-XJGEX  Month-to-month      49          103.70
26    6467-CHFZW  Month-to-month      47           99.35
38    5380-WJKOV  Month-to-month      34          106.35
...          ...             ...     ...             ...
6972  6664-FPDAC        One year      56          111.95
6986  3976-BWUCK  Month-to-month      30           94.10
6991  3585-ISXZP  Month-to-month       8           95.65
6993  6583-QGCSI  Month-to-month      50           88.05
7006  0093-XWZFY  Month-to-month      40          104.50

[904 rows x 4 columns]

In [182]:
print("Total customers already churned and were paying more than $80 per month:", len(churned_high_paying))

Total customers already churned and were paying more than $80 per month: 904

## Exercise 5: Identify short-tenure churn

A new-customer retention program is being considered. The team wants to understand customers who churned within their first **12 months**.

1. Filter for `Churn == 'Yes'` and `tenure <= 12`.
2. Display `customerID`, `Contract`, `tenure`, `MonthlyCharges`, and `InternetService`.
3. Calculate the average `MonthlyCharges` for this group.

**Business question:** Is early churn concentrated among customers with relatively low or relatively high monthly charges?

In [183]:
# Your work here
churned_12_months = data[
    (data["Churn"] == "Yes") &
    (data["tenure"] <= 12)
]

churned_12_months = churned_12_months[
    ["customerID", "Contract", "tenure", "MonthlyCharges", "InternetService"]
]
print(churned_12_months)

      customerID        Contract  tenure  MonthlyCharges InternetService
2     3668-QPYBK  Month-to-month       2           53.85             DSL
4     9237-HQITU  Month-to-month       2           70.70     Fiber optic
5     9305-CDSKC  Month-to-month       8           99.65     Fiber optic
18    4190-MFLUW  Month-to-month      10           55.20             DSL
20    8779-QRDMV  Month-to-month       1           39.65             DSL
...          ...             ...     ...             ...             ...
6970  8083-YTZES  Month-to-month       4           74.35     Fiber optic
6991  3585-ISXZP  Month-to-month       8           95.65     Fiber optic
6999  2108-XWMPY  Month-to-month       3           35.45             DSL
7001  6304-IJFSQ  Month-to-month       3           49.90             DSL
7008  1980-KXVPM  Month-to-month       3           75.05     Fiber optic

[1030 rows x 5 columns]

In [184]:
average_monthly_charges = churned_12_months["MonthlyCharges"].mean()
print("Average Monthly Charges:", average_monthly_charges)

Average Monthly Charges: 66.49961165048545

---
# Part 3 — NumPy for Customer Metrics

## Exercise 6: Analyze monthly charges with a NumPy array

The finance team wants a simple numerical summary of monthly charges.

1. Convert the `MonthlyCharges` column into a NumPy array called `monthly_charges`.
2. Calculate:
   - mean
   - median
   - minimum
   - maximum
3. Count how many customers pay **more than $100 per month**.
4. Count how many customers pay **less than $50 per month**.

**Business question:** How spread out are the company's monthly customer charges, and how many customers are in the high-charge segment?

In [185]:
# Your work here
monthly_charges = data["MonthlyCharges"].to_numpy()
# monthly_charges = data["MonthlyCharges"]
monthly_charges

array([ 29.85,  56.95,  53.85, ..., 104.5 ,  63.1 ,  75.05], shape=(7009,))

In [186]:
mean = np.mean(monthly_charges)
median = np.median(monthly_charges)
minimum = np.min(monthly_charges)
maximum = np.max(monthly_charges)

print("Mean:", mean)
print("Median:", median)
print("Minimum:", minimum)
print("Maximum:", maximum)

Mean: 64.74630475103439
Median: 70.35
Minimum: 18.25
Maximum: 118.75

In [187]:
more_than_100 = np.sum(monthly_charges > 100)
print("Customers paying more than $100:", more_than_100)

Customers paying more than $100: 897

In [188]:
less_than_50 = np.sum(monthly_charges < 50)
print("Customers paying less than $50:", less_than_50)

Customers paying less than $50: 2285

## Exercise 7: Create a simple revenue-at-risk metric

For this classroom exercise, assume that if a customer churns, the company loses one month of that customer's current recurring charge.

1. Create a NumPy array containing `MonthlyCharges` for churned customers only.
2. Calculate the total monthly revenue represented by churned customers.
3. Calculate the average monthly charge of churned customers.
4. Use NumPy to find the highest monthly charge among churned customers.

**Business question:** Approximately how much monthly recurring revenue is represented by customers who have already churned?

In [189]:
# Your work here
churned_customers = data[data["Churn"] == "Yes"]
# churned_customers.sample()
churned_monthly_charges = churned_customers["MonthlyCharges"].to_numpy()
churned_monthly_charges

array([ 53.85,  70.7 ,  99.65, ...,  49.9 , 104.5 ,  75.05], shape=(1860,))

In [190]:
total_churned_revenue = np.sum(churned_monthly_charges)
print("Total monthly revenue by churned customers:", total_churned_revenue)

Total monthly revenue by churned customers: 138487.25

In [191]:
average_churned_charge = np.mean(churned_monthly_charges)
print("Average monthly charge of churned customers:", average_churned_charge)

Average monthly charge of churned customers: 74.45551075268817

In [192]:
highest_churned_charge = np.max(churned_monthly_charges)
print("Highest monthly charge among churned customers:", highest_churned_charge)

Highest monthly charge among churned customers: 118.35

## Exercise 8: Flag unusually expensive customers

The retention team wants a simple rule for identifying customers with charges above the overall average.

1. Calculate the average `MonthlyCharges`.
2. Create a Boolean NumPy array that is `True` when a customer's monthly charge is greater than the overall average.
3. Count the number of `True` values.
4. Use the Boolean array to create a NumPy array containing only customers above the average monthly charge.

**Business question:** How large is the above-average customer segment?

In [193]:
# Your work here
monthly_charges = data["MonthlyCharges"].to_numpy()
average_charge = np.mean(monthly_charges)
average_charge = round(average_charge, 2)
print("Average monthly charge:", average_charge)

Average monthly charge: 64.75

In [194]:
above_average = monthly_charges > average_charge
# above_average.tolist()

In [195]:
count_above_average = np.sum(above_average)
print("Count of above average customers:", count_above_average)

Count of above average customers: 3903

In [196]:
above_average_charges = monthly_charges[above_average]

print("Above average charges:")
print(above_average_charges)

Above average charges:
[ 70.7   99.65  89.1  ...  95.1  104.5   75.05]

---
# Part 4 — Customer Segmentation with Pandas

## Exercise 9: Compare contract types

Management is considering whether contract type is related to customer value.

Use `groupby()` to calculate the **average `MonthlyCharges`** for each `Contract` type.

Then calculate the **average `tenure`** for each `Contract` type.

**Business question:** Which contract type has the highest average monthly charge? Which has the longest average tenure?

In [197]:
# Your work here
average_monthly_charges = data.groupby("Contract")["MonthlyCharges"].mean()
print(average_monthly_charges)

Contract
Month-to-month    66.383195
One year          64.991956
Two year          60.798816
Name: MonthlyCharges, dtype: float64

In [198]:
average_tenure = data.groupby("Contract")["tenure"].mean()
print(average_tenure)

Contract
Month-to-month    18.022320
One year          42.048398
Two year          56.724689
Name: tenure, dtype: float64

In [199]:
result = data.groupby("Contract")[["MonthlyCharges", "tenure"]].mean()
print(result)

                MonthlyCharges     tenure
Contract
Month-to-month       66.383195  18.022320
One year             64.991956  42.048398
Two year             60.798816  56.724689

## Exercise 10: Compare churn within contract types

The marketing team wants to know whether some contract types appear more exposed to churn.

1. Group the data by `Contract` and `Churn`.
2. Count the number of customers in each combination.
3. Create a pivot table with:
   - rows: `Contract`
   - columns: `Churn`
   - values: customer counts

**Business question:** Which contract type has the largest number of churned customers?

In [200]:
# Your work here
grouped = data.groupby(["Contract", "Churn"])

In [201]:
customer_counts = data.groupby(["Contract", "Churn"])["customerID"].count()
print(customer_counts)

Contract        Churn
Month-to-month  No       2206
                Yes      1647
One year        No       1302
                Yes       165
Two year        No       1641
                Yes        48
Name: customerID, dtype: int64

In [202]:
pivot = pd.pivot_table(
    data,
    index="Contract",
    columns="Churn",
    values="customerID",
    aggfunc="count"
)

print(pivot)

Churn             No   Yes
Contract
Month-to-month  2206  1647
One year        1302   165
Two year        1641    48

## Exercise 11: Find the customer segment with the highest average monthly charge

The business is deciding where to focus a premium-service campaign.

Use `groupby()` to calculate average `MonthlyCharges` for each combination of:
- `gender`
- `Contract`

**Business question:** Which gender/contract combination has the highest average monthly charge?

Do not assume that the highest-paying group is automatically the best target—use the result as a starting point for further analysis.

In [203]:
# Your work here
average_charges = data.groupby(
    ["gender", 
     "Contract"]
)["MonthlyCharges"].mean()

print(average_charges)

gender  Contract
Female  Month-to-month    66.660580
        One year          66.799511
        Two year          60.622381
Male    Month-to-month    66.109386
        One year          63.268642
        Two year          60.973380
Name: MonthlyCharges, dtype: float64

---
# Part 5 — Retention Strategy

## Exercise 12: Profile churned customers

The retention team wants a compact summary of churned customers.

1. Create a DataFrame containing only churned customers.
2. Create a pivot table with:
   - index: `Contract`
   - values: `tenure` and `MonthlyCharges`
   - aggregation functions: `np.mean`, `np.median`, and `np.max`

**Business question:** For each contract type, what do the typical and highest-value churned customers look like?

In [204]:
# Your work here
churned_customers = data[data["Churn"] == "Yes"]
# print(churned_customers)

In [205]:
pivot = pd.pivot_table(
    churned_customers,
    index="Contract",
    values=["tenure", "MonthlyCharges"],
    aggfunc=["mean", "median", "max"]
)

print(pivot)

                         mean                    median                   max  \
               MonthlyCharges     tenure MonthlyCharges tenure MonthlyCharges
Contract
Month-to-month      73.019611  14.018215         79.100    7.0         117.45
One year            85.203939  45.163636         95.250   48.0         118.35
Two year            86.777083  61.270833         97.275   65.5         116.20


               tenure
Contract
Month-to-month     71
One year           72
Two year           72

## Exercise 13: Investigate month-to-month churn

Month-to-month customers are a key group for the retention team.

1. Create a DataFrame containing customers who:
   - have `Contract == 'Month-to-month'`
   - have `Churn == 'Yes'`
2. Use `describe()` to summarize the numerical columns.
3. Create a pivot table using:
   - index: `gender`, `Partner`, `Dependents`
   - values: `tenure` and `MonthlyCharges`
   - aggregation functions: `np.mean` and `np.median`

**Business question:** Are there noticeable differences in tenure and monthly charges among different customer profiles within the month-to-month churned group?

In [206]:
# Your work here
# unique_contract = data["Contract"].unique()
# unique_contract.tolist()

# unique_Churn = data["Churn"].unique()
# unique_Churn.tolist()

month_churned = data[
    (data["Contract"] == "Month-to-month") &
    (data["Churn"] == "Yes")
]

print(month_churned)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
2     3668-QPYBK    Male              0      No         No       2
4     9237-HQITU  Female              0      No         No       2
5     9305-CDSKC  Female              0      No         No       8
8     7892-POOKP  Female              0     Yes         No      28
13    0280-XJGEX    Male              0      No         No      49
...          ...     ...            ...     ...        ...     ...
6993  6583-QGCSI  Female              1     Yes         No      50
6999  2108-XWMPY    Male              0      No         No       3
7001  6304-IJFSQ    Male              0      No         No       3
7006  0093-XWZFY    Male              0      No         No      40
7008  1980-KXVPM  Female              1      No         No       3

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
2             Yes                No             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
5             Yes               Yes     Fiber optic             No  ...
8             Yes               Yes     Fiber optic             No  ...
13            Yes               Yes     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
6993          Yes               Yes     Fiber optic             No  ...
6999           No  No phone service             DSL            Yes  ...
7001          Yes                No             DSL             No  ...
7006          Yes               Yes     Fiber optic             No  ...
7008          Yes               Yes     Fiber optic             No  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
2                  No          No          No              No  Month-to-month
4                  No          No          No              No  Month-to-month
5                 Yes          No         Yes             Yes  Month-to-month
8                 Yes         Yes         Yes             Yes  Month-to-month
13                Yes          No         Yes             Yes  Month-to-month
...               ...         ...         ...             ...             ...
6993               No          No         Yes              No  Month-to-month
6999               No          No          No              No  Month-to-month
7001               No          No          No              No  Month-to-month
7006              Yes          No         Yes             Yes  Month-to-month
7008               No          No          No              No  Month-to-month

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
2                 Yes               Mailed check          53.85        108.15
4                 Yes           Electronic check          70.70        151.65
5                 Yes           Electronic check          99.65         820.5
8                 Yes           Electronic check         104.80       3046.05
13                Yes  Bank transfer (automatic)         103.70        5036.3
...               ...                        ...            ...           ...
6993              Yes           Electronic check          88.05       4367.35
6999              Yes               Mailed check          35.45        106.85
7001              Yes               Mailed check          49.90         130.1
7006              Yes    Credit card (automatic)         104.50       4036.85
7008              Yes    Credit card (automatic)          75.05        256.25

     Churn
2      Yes
4      Yes
5      Yes
8      Yes
13     Yes
...    ...
6993   Yes
6999   Yes
7001   Yes
7006   Yes
7008   Yes

[1647 rows x 21 columns]

In [207]:
month_churned.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    1647.000000  1647.000000     1647.000000
mean        0.265938    14.018215       73.019611
std         0.441966    15.797539       24.117849
min         0.000000     1.000000       18.850000
25%         0.000000     2.000000       55.175000
50%         0.000000     7.000000       79.100000
75%         1.000000    21.000000       90.950000
max         1.000000    71.000000      117.450000

In [208]:
pivot = pd.pivot_table(
    month_churned,
    index=["gender", "Partner", "Dependents"],
    values=["tenure", "MonthlyCharges"],
    aggfunc=["mean", "median"]
)

print(pivot)

                                    mean                    median
                          MonthlyCharges     tenure MonthlyCharges tenure
gender Partner Dependents
Female No      No              72.432058  10.710383         76.500    5.0
               Yes             66.387500   8.285714         71.950    4.0
       Yes     No              79.495130  20.902597         84.325   16.0
               Yes             71.363551  18.299065         80.500   13.0
Male   No      No              69.221907  10.819473         74.950    5.0
               Yes             62.871250   9.800000         69.700    3.0
       Yes     No              82.310363  23.113990         85.600   17.0
               Yes             75.107831  19.421687         80.150   15.0

## Exercise 14: Make a short business recommendation

Use the results from the previous exercises to answer these questions in **3–5 sentences**:

1. Which customer group would you investigate first for a retention campaign?
2. What evidence from the dataset supports your choice?
3. What additional analysis would you want before launching a campaign?


Your recommendation should be based on your calculations rather than assumptions.

# Write your recommendation here.
I think I would investigate Month-month customers who churned in their first 12 months for retention campaign. Based on analysis or what shows in the datasets, it seems customers are leaving early and their monthly charges indicate how much recurring revenue could be lost when they churn. Their monthly charges can also help estimate the recurring revenue at risk from churn. Before launching the campaign, I would analyze the reasons for churn and compare churn rates across different customer groups.

---
# Optional Challenge — NumPy and Customer Tenure

A customer-success manager wants to divide customers into three simple tenure groups:

- **New:** 0–12 months
- **Established:** 13–48 months
- **Long-term:** more than 48 months

Using NumPy:

1. Create a NumPy array of customer tenure.
2. Create Boolean conditions for the three groups.
3. Count the number of customers in each group.
4. For each group, calculate the average monthly charge using the original Pandas data and the corresponding Boolean condition.

**Business question:** Which tenure group represents the largest customer base, and which group has the highest average monthly charge?

In [209]:
# Your work here
tenure = data["tenure"].to_numpy()

In [210]:
new = (tenure >= 0) & (tenure <= 12)
established = (tenure >= 13) & (tenure <= 48)
long_term = tenure > 48

In [211]:
print("New:", np.sum(new))
print("Established:", np.sum(established))
print("Long-term:", np.sum(long_term))

New: 2173
Established: 2607
Long-term: 2229

In [212]:
new_avg_charge = data.loc[new, "MonthlyCharges"].mean()
established_avg_charge = data.loc[established, "MonthlyCharges"].mean()
long_term_avg_charge = data.loc[long_term, "MonthlyCharges"].mean()

print("\nAverage Monthly Charge:")
print("New:", new_avg_charge)
print("Established:", established_avg_charge)
print("Long-term:", long_term_avg_charge)

Average Monthly Charge:
New: 56.11884491486424
Established: 64.084388185654
Long-term: 73.93117990130104

## End of Activity

Before submitting, make sure:
- your code runs from top to bottom;
- you used the requested Pandas/NumPy techniques;
- your business conclusions are supported by your calculations;
- you did not modify the original dataset accidentally.